name: 'dbt_project'
version: '1.0.0'
config-version: 2

profile: 'dev'

model-paths: ["models"]
test-paths: ["tests"]

models:
  dbt_project:
      staging:
          schema: staging
          +materialized: view
      intermediate:
          schema: intermediate
          +materialized: view
      mart:
          schema: mart
          +materialized: table